### ISSUE TITLE
problem with the link generation

### ISSUE THREAD

**Issue by tusharhero** [tusharhero/asciificationpy#3]
`x**2/4**2 + y**2/7**2 <= 1` when we put this equation in. 
we get the following link
https://tusharhero.xyz/asciificationpy/?eqt=x**2%2F4**2+++y**2%2F7**2+%3C%3D+1&size=21

but when we open it we get
`x**2/4**2   y**2/7**2 <= 1`

**Comment by tusharhero** [comment]
@biologyscience the + is missing

**Comment by biologyscience** [comment]
~~https://tusharhero.xyz/asciificationpy/?eqt=x**2%2F4**2+++y**2%2F7**2+%3C%3D+1&size=21~~

https://tusharhero.xyz/asciificationpy/?eqt=x**2%2F4**2%20plus%20y**2%2F7**2+%3C%3D+1&size=21

**Comment by tusharhero** [comment]
As this issue is solved now i am closing it.
